- name: Stat google-cloud-sdk commands
  stat:
    path: '/usr/bin/{{ item }}'
  loop:
  - gcloud
  - gsutil
  register: stat_google_cloud_sdk

- name: Ensure {{ gcloud_install_dir }}/google-cloud-sdk is not already present
  file:
    path: '{{ gcloud_install_dir }}/google-cloud-sdk'
    state: absent
  when: false in stat_google_cloud_sdk.results | map(attribute="stat.exists") | list

- name: unarchive google-cloud-sdk
  unarchive:
    src: '{{ cloudsdk_url }}'
    dest: '{{ gcloud_install_dir }}'
    remote_src: true
    creates: '{{ gcloud_install_dir }}/google-cloud-sdk'
  when: false in stat_google_cloud_sdk.results | map(attribute="stat.exists") | list

- name: updating alternatives
  command: >-
    update-alternatives --install /usr/bin/{{ item.item }} {{ item.item }}
    {{ gcloud_install_dir }}/google-cloud-sdk/bin/{{ item.item }} 1 --force
  loop: '{{ stat_google_cloud_sdk.results }}'
  when: not item.stat.exists